[build]
  functions = ".netlify/functions"
  publish = "public"
  command = "npm run build"
  functionsSource = "functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[dev]
  functions = "functions"
  publish = "public"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
